/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDarajaCallbackRouteImport } from './routes/api/public/daraja-callback'
import { Route as ApiPublicArchiveExpiredRecordsRouteImport } from './routes/api/public/archive-expired-records'
import { Route as ApiMobileUploadsRouteImport } from './routes/api/mobile/uploads'
import { Route as ApiMobileSettingsRouteImport } from './routes/api/mobile/settings'
import { Route as ApiMobileSearchRouteImport } from './routes/api/mobile/search'
import { Route as ApiMobilePaymentsRouteImport } from './routes/api/mobile/payments'
import { Route as ApiMobilePaymentNotificationsRouteImport } from './routes/api/mobile/payment-notifications'
import { Route as ApiMobilePackagesRouteImport } from './routes/api/mobile/packages'
import { Route as ApiMobileNotificationsRouteImport } from './routes/api/mobile/notifications'
import { Route as ApiMobileCustomersRouteImport } from './routes/api/mobile/customers'
import { Route as ApiMobileCommissionsRouteImport } from './routes/api/mobile/commissions'
import { Route as ApiMobileAppUpdatesRouteImport } from './routes/api/mobile/app-updates'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiMobileStatsHomeRouteImport } from './routes/api/mobile/stats.home'
import { Route as ApiMobileStatsDashboardRouteImport } from './routes/api/mobile/stats.dashboard'
import { Route as ApiMobilePushRegisterRouteImport } from './routes/api/mobile/push.register'
import { Route as ApiMobilePaymentsManualRouteImport } from './routes/api/mobile/payments.manual'
import { Route as ApiMobilePaymentsIdRouteImport } from './routes/api/mobile/payments.$id'
import { Route as ApiMobilePaymentNotificationsAuditRouteImport } from './routes/api/mobile/payment-notifications.audit'
import { Route as ApiMobilePaymentNotificationsIdRouteImport } from './routes/api/mobile/payment-notifications.$id'
import { Route as ApiMobilePackagesScanRouteImport } from './routes/api/mobile/packages.scan'
import { Route as ApiMobilePackagesClearedRouteImport } from './routes/api/mobile/packages.cleared'
import { Route as ApiMobilePackagesIdRouteImport } from './routes/api/mobile/packages.$id'
import { Route as ApiMobileCustomersVerifyRouteImport } from './routes/api/mobile/customers.verify'
import { Route as ApiMobileCustomersIdRouteImport } from './routes/api/mobile/customers.$id'
import { Route as ApiMobileCommissionsIdRouteImport } from './routes/api/mobile/commissions.$id'
import { Route as ApiMobileAuthMeRouteImport } from './routes/api/mobile/auth.me'
import { Route as ApiMobileAdminEmployeesRouteImport } from './routes/api/mobile/admin/employees'
import { Route as ApiMobileAdminAuditRouteImport } from './routes/api/mobile/admin/audit'
import { Route as ApiMobilePaymentNotificationsIdLinkRouteImport } from './routes/api/mobile/payment-notifications.$id.link'
import { Route as ApiMobilePackagesIdTransitionRouteImport } from './routes/api/mobile/packages.$id.transition'
import { Route as ApiMobilePackagesIdCollectRouteImport } from './routes/api/mobile/packages.$id.collect'
import { Route as ApiMobileAdminEmployeesIdRouteImport } from './routes/api/mobile/admin/employees.$id'
import { Route as ApiAdminUsersIdRolesRouteImport } from './routes/api/admin/users.$id.roles'
import { Route as ApiMobileAdminEmployeesIdResetPasswordRouteImport } from './routes/api/mobile/admin/employees.$id.reset-password'
import { Route as ApiMobileAdminEmployeesIdActivityRouteImport } from './routes/api/mobile/admin/employees.$id.activity'

const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDarajaCallbackRoute = ApiPublicDarajaCallbackRouteImport.update({
  id: '/api/public/daraja-callback',
  path: '/api/public/daraja-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArchiveExpiredRecordsRoute =
  ApiPublicArchiveExpiredRecordsRouteImport.update({
    id: '/api/public/archive-expired-records',
    path: '/api/public/archive-expired-records',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileUploadsRoute = ApiMobileUploadsRouteImport.update({
  id: '/api/mobile/uploads',
  path: '/api/mobile/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileSettingsRoute = ApiMobileSettingsRouteImport.update({
  id: '/api/mobile/settings',
  path: '/api/mobile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileSearchRoute = ApiMobileSearchRouteImport.update({
  id: '/api/mobile/search',
  path: '/api/mobile/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobilePaymentsRoute = ApiMobilePaymentsRouteImport.update({
  id: '/api/mobile/payments',
  path: '/api/mobile/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobilePaymentNotificationsRoute =
  ApiMobilePaymentNotificationsRouteImport.update({
    id: '/api/mobile/payment-notifications',
    path: '/api/mobile/payment-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobilePackagesRoute = ApiMobilePackagesRouteImport.update({
  id: '/api/mobile/packages',
  path: '/api/mobile/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileNotificationsRoute = ApiMobileNotificationsRouteImport.update({
  id: '/api/mobile/notifications',
  path: '/api/mobile/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileCustomersRoute = ApiMobileCustomersRouteImport.update({
  id: '/api/mobile/customers',
  path: '/api/mobile/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileCommissionsRoute = ApiMobileCommissionsRouteImport.update({
  id: '/api/mobile/commissions',
  path: '/api/mobile/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAppUpdatesRoute = ApiMobileAppUpdatesRouteImport.update({
  id: '/api/mobile/app-updates',
  path: '/api/mobile/app-updates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileStatsHomeRoute = ApiMobileStatsHomeRouteImport.update({
  id: '/api/mobile/stats/home',
  path: '/api/mobile/stats/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileStatsDashboardRoute = ApiMobileStatsDashboardRouteImport.update({
  id: '/api/mobile/stats/dashboard',
  path: '/api/mobile/stats/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobilePushRegisterRoute = ApiMobilePushRegisterRouteImport.update({
  id: '/api/mobile/push/register',
  path: '/api/mobile/push/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobilePaymentsManualRoute = ApiMobilePaymentsManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => ApiMobilePaymentsRoute,
} as any)
const ApiMobilePaymentsIdRoute = ApiMobilePaymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMobilePaymentsRoute,
} as any)
const ApiMobilePaymentNotificationsAuditRoute =
  ApiMobilePaymentNotificationsAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => ApiMobilePaymentNotificationsRoute,
  } as any)
const ApiMobilePaymentNotificationsIdRoute =
  ApiMobilePaymentNotificationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiMobilePaymentNotificationsRoute,
  } as any)
const ApiMobilePackagesScanRoute = ApiMobilePackagesScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => ApiMobilePackagesRoute,
} as any)
const ApiMobilePackagesClearedRoute =
  ApiMobilePackagesClearedRouteImport.update({
    id: '/cleared',
    path: '/cleared',
    getParentRoute: () => ApiMobilePackagesRoute,
  } as any)
const ApiMobilePackagesIdRoute = ApiMobilePackagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMobilePackagesRoute,
} as any)
const ApiMobileCustomersVerifyRoute =
  ApiMobileCustomersVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => ApiMobileCustomersRoute,
  } as any)
const ApiMobileCustomersIdRoute = ApiMobileCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMobileCustomersRoute,
} as any)
const ApiMobileCommissionsIdRoute = ApiMobileCommissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMobileCommissionsRoute,
} as any)
const ApiMobileAuthMeRoute = ApiMobileAuthMeRouteImport.update({
  id: '/api/mobile/auth/me',
  path: '/api/mobile/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAdminEmployeesRoute = ApiMobileAdminEmployeesRouteImport.update({
  id: '/api/mobile/admin/employees',
  path: '/api/mobile/admin/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAdminAuditRoute = ApiMobileAdminAuditRouteImport.update({
  id: '/api/mobile/admin/audit',
  path: '/api/mobile/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobilePaymentNotificationsIdLinkRoute =
  ApiMobilePaymentNotificationsIdLinkRouteImport.update({
    id: '/link',
    path: '/link',
    getParentRoute: () => ApiMobilePaymentNotificationsIdRoute,
  } as any)
const ApiMobilePackagesIdTransitionRoute =
  ApiMobilePackagesIdTransitionRouteImport.update({
    id: '/transition',
    path: '/transition',
    getParentRoute: () => ApiMobilePackagesIdRoute,
  } as any)
const ApiMobilePackagesIdCollectRoute =
  ApiMobilePackagesIdCollectRouteImport.update({
    id: '/collect',
    path: '/collect',
    getParentRoute: () => ApiMobilePackagesIdRoute,
  } as any)
const ApiMobileAdminEmployeesIdRoute =
  ApiMobileAdminEmployeesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiMobileAdminEmployeesRoute,
  } as any)
const ApiAdminUsersIdRolesRoute = ApiAdminUsersIdRolesRouteImport.update({
  id: '/$id/roles',
  path: '/$id/roles',
  getParentRoute: () => ApiAdminUsersRoute,
} as any)
const ApiMobileAdminEmployeesIdResetPasswordRoute =
  ApiMobileAdminEmployeesIdResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => ApiMobileAdminEmployeesIdRoute,
  } as any)
const ApiMobileAdminEmployeesIdActivityRoute =
  ApiMobileAdminEmployeesIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => ApiMobileAdminEmployeesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ops': typeof OpsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/mobile/app-updates': typeof ApiMobileAppUpdatesRoute
  '/api/mobile/commissions': typeof ApiMobileCommissionsRouteWithChildren
  '/api/mobile/customers': typeof ApiMobileCustomersRouteWithChildren
  '/api/mobile/notifications': typeof ApiMobileNotificationsRoute
  '/api/mobile/packages': typeof ApiMobilePackagesRouteWithChildren
  '/api/mobile/payment-notifications': typeof ApiMobilePaymentNotificationsRouteWithChildren
  '/api/mobile/payments': typeof ApiMobilePaymentsRouteWithChildren
  '/api/mobile/search': typeof ApiMobileSearchRoute
  '/api/mobile/settings': typeof ApiMobileSettingsRoute
  '/api/mobile/uploads': typeof ApiMobileUploadsRoute
  '/api/public/archive-expired-records': typeof ApiPublicArchiveExpiredRecordsRoute
  '/api/public/daraja-callback': typeof ApiPublicDarajaCallbackRoute
  '/api/mobile/admin/audit': typeof ApiMobileAdminAuditRoute
  '/api/mobile/admin/employees': typeof ApiMobileAdminEmployeesRouteWithChildren
  '/api/mobile/auth/me': typeof ApiMobileAuthMeRoute
  '/api/mobile/commissions/$id': typeof ApiMobileCommissionsIdRoute
  '/api/mobile/customers/$id': typeof ApiMobileCustomersIdRoute
  '/api/mobile/customers/verify': typeof ApiMobileCustomersVerifyRoute
  '/api/mobile/packages/$id': typeof ApiMobilePackagesIdRouteWithChildren
  '/api/mobile/packages/cleared': typeof ApiMobilePackagesClearedRoute
  '/api/mobile/packages/scan': typeof ApiMobilePackagesScanRoute
  '/api/mobile/payment-notifications/$id': typeof ApiMobilePaymentNotificationsIdRouteWithChildren
  '/api/mobile/payment-notifications/audit': typeof ApiMobilePaymentNotificationsAuditRoute
  '/api/mobile/payments/$id': typeof ApiMobilePaymentsIdRoute
  '/api/mobile/payments/manual': typeof ApiMobilePaymentsManualRoute
  '/api/mobile/push/register': typeof ApiMobilePushRegisterRoute
  '/api/mobile/stats/dashboard': typeof ApiMobileStatsDashboardRoute
  '/api/mobile/stats/home': typeof ApiMobileStatsHomeRoute
  '/api/admin/users/$id/roles': typeof ApiAdminUsersIdRolesRoute
  '/api/mobile/admin/employees/$id': typeof ApiMobileAdminEmployeesIdRouteWithChildren
  '/api/mobile/packages/$id/collect': typeof ApiMobilePackagesIdCollectRoute
  '/api/mobile/packages/$id/transition': typeof ApiMobilePackagesIdTransitionRoute
  '/api/mobile/payment-notifications/$id/link': typeof ApiMobilePaymentNotificationsIdLinkRoute
  '/api/mobile/admin/employees/$id/activity': typeof ApiMobileAdminEmployeesIdActivityRoute
  '/api/mobile/admin/employees/$id/reset-password': typeof ApiMobileAdminEmployeesIdResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ops': typeof OpsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/mobile/app-updates': typeof ApiMobileAppUpdatesRoute
  '/api/mobile/commissions': typeof ApiMobileCommissionsRouteWithChildren
  '/api/mobile/customers': typeof ApiMobileCustomersRouteWithChildren
  '/api/mobile/notifications': typeof ApiMobileNotificationsRoute
  '/api/mobile/packages': typeof ApiMobilePackagesRouteWithChildren
  '/api/mobile/payment-notifications': typeof ApiMobilePaymentNotificationsRouteWithChildren
  '/api/mobile/payments': typeof ApiMobilePaymentsRouteWithChildren
  '/api/mobile/search': typeof ApiMobileSearchRoute
  '/api/mobile/settings': typeof ApiMobileSettingsRoute
  '/api/mobile/uploads': typeof ApiMobileUploadsRoute
  '/api/public/archive-expired-records': typeof ApiPublicArchiveExpiredRecordsRoute
  '/api/public/daraja-callback': typeof ApiPublicDarajaCallbackRoute
  '/api/mobile/admin/audit': typeof ApiMobileAdminAuditRoute
  '/api/mobile/admin/employees': typeof ApiMobileAdminEmployeesRouteWithChildren
  '/api/mobile/auth/me': typeof ApiMobileAuthMeRoute
  '/api/mobile/commissions/$id': typeof ApiMobileCommissionsIdRoute
  '/api/mobile/customers/$id': typeof ApiMobileCustomersIdRoute
  '/api/mobile/customers/verify': typeof ApiMobileCustomersVerifyRoute
  '/api/mobile/packages/$id': typeof ApiMobilePackagesIdRouteWithChildren
  '/api/mobile/packages/cleared': typeof ApiMobilePackagesClearedRoute
  '/api/mobile/packages/scan': typeof ApiMobilePackagesScanRoute
  '/api/mobile/payment-notifications/$id': typeof ApiMobilePaymentNotificationsIdRouteWithChildren
  '/api/mobile/payment-notifications/audit': typeof ApiMobilePaymentNotificationsAuditRoute
  '/api/mobile/payments/$id': typeof ApiMobilePaymentsIdRoute
  '/api/mobile/payments/manual': typeof ApiMobilePaymentsManualRoute
  '/api/mobile/push/register': typeof ApiMobilePushRegisterRoute
  '/api/mobile/stats/dashboard': typeof ApiMobileStatsDashboardRoute
  '/api/mobile/stats/home': typeof ApiMobileStatsHomeRoute
  '/api/admin/users/$id/roles': typeof ApiAdminUsersIdRolesRoute
  '/api/mobile/admin/employees/$id': typeof ApiMobileAdminEmployeesIdRouteWithChildren
  '/api/mobile/packages/$id/collect': typeof ApiMobilePackagesIdCollectRoute
  '/api/mobile/packages/$id/transition': typeof ApiMobilePackagesIdTransitionRoute
  '/api/mobile/payment-notifications/$id/link': typeof ApiMobilePaymentNotificationsIdLinkRoute
  '/api/mobile/admin/employees/$id/activity': typeof ApiMobileAdminEmployeesIdActivityRoute
  '/api/mobile/admin/employees/$id/reset-password': typeof ApiMobileAdminEmployeesIdResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ops': typeof OpsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/mobile/app-updates': typeof ApiMobileAppUpdatesRoute
  '/api/mobile/commissions': typeof ApiMobileCommissionsRouteWithChildren
  '/api/mobile/customers': typeof ApiMobileCustomersRouteWithChildren
  '/api/mobile/notifications': typeof ApiMobileNotificationsRoute
  '/api/mobile/packages': typeof ApiMobilePackagesRouteWithChildren
  '/api/mobile/payment-notifications': typeof ApiMobilePaymentNotificationsRouteWithChildren
  '/api/mobile/payments': typeof ApiMobilePaymentsRouteWithChildren
  '/api/mobile/search': typeof ApiMobileSearchRoute
  '/api/mobile/settings': typeof ApiMobileSettingsRoute
  '/api/mobile/uploads': typeof ApiMobileUploadsRoute
  '/api/public/archive-expired-records': typeof ApiPublicArchiveExpiredRecordsRoute
  '/api/public/daraja-callback': typeof ApiPublicDarajaCallbackRoute
  '/api/mobile/admin/audit': typeof ApiMobileAdminAuditRoute
  '/api/mobile/admin/employees': typeof ApiMobileAdminEmployeesRouteWithChildren
  '/api/mobile/auth/me': typeof ApiMobileAuthMeRoute
  '/api/mobile/commissions/$id': typeof ApiMobileCommissionsIdRoute
  '/api/mobile/customers/$id': typeof ApiMobileCustomersIdRoute
  '/api/mobile/customers/verify': typeof ApiMobileCustomersVerifyRoute
  '/api/mobile/packages/$id': typeof ApiMobilePackagesIdRouteWithChildren
  '/api/mobile/packages/cleared': typeof ApiMobilePackagesClearedRoute
  '/api/mobile/packages/scan': typeof ApiMobilePackagesScanRoute
  '/api/mobile/payment-notifications/$id': typeof ApiMobilePaymentNotificationsIdRouteWithChildren
  '/api/mobile/payment-notifications/audit': typeof ApiMobilePaymentNotificationsAuditRoute
  '/api/mobile/payments/$id': typeof ApiMobilePaymentsIdRoute
  '/api/mobile/payments/manual': typeof ApiMobilePaymentsManualRoute
  '/api/mobile/push/register': typeof ApiMobilePushRegisterRoute
  '/api/mobile/stats/dashboard': typeof ApiMobileStatsDashboardRoute
  '/api/mobile/stats/home': typeof ApiMobileStatsHomeRoute
  '/api/admin/users/$id/roles': typeof ApiAdminUsersIdRolesRoute
  '/api/mobile/admin/employees/$id': typeof ApiMobileAdminEmployeesIdRouteWithChildren
  '/api/mobile/packages/$id/collect': typeof ApiMobilePackagesIdCollectRoute
  '/api/mobile/packages/$id/transition': typeof ApiMobilePackagesIdTransitionRoute
  '/api/mobile/payment-notifications/$id/link': typeof ApiMobilePaymentNotificationsIdLinkRoute
  '/api/mobile/admin/employees/$id/activity': typeof ApiMobileAdminEmployeesIdActivityRoute
  '/api/mobile/admin/employees/$id/reset-password': typeof ApiMobileAdminEmployeesIdResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ops'
    | '/api/admin/users'
    | '/api/mobile/app-updates'
    | '/api/mobile/commissions'
    | '/api/mobile/customers'
    | '/api/mobile/notifications'
    | '/api/mobile/packages'
    | '/api/mobile/payment-notifications'
    | '/api/mobile/payments'
    | '/api/mobile/search'
    | '/api/mobile/settings'
    | '/api/mobile/uploads'
    | '/api/public/archive-expired-records'
    | '/api/public/daraja-callback'
    | '/api/mobile/admin/audit'
    | '/api/mobile/admin/employees'
    | '/api/mobile/auth/me'
    | '/api/mobile/commissions/$id'
    | '/api/mobile/customers/$id'
    | '/api/mobile/customers/verify'
    | '/api/mobile/packages/$id'
    | '/api/mobile/packages/cleared'
    | '/api/mobile/packages/scan'
    | '/api/mobile/payment-notifications/$id'
    | '/api/mobile/payment-notifications/audit'
    | '/api/mobile/payments/$id'
    | '/api/mobile/payments/manual'
    | '/api/mobile/push/register'
    | '/api/mobile/stats/dashboard'
    | '/api/mobile/stats/home'
    | '/api/admin/users/$id/roles'
    | '/api/mobile/admin/employees/$id'
    | '/api/mobile/packages/$id/collect'
    | '/api/mobile/packages/$id/transition'
    | '/api/mobile/payment-notifications/$id/link'
    | '/api/mobile/admin/employees/$id/activity'
    | '/api/mobile/admin/employees/$id/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ops'
    | '/api/admin/users'
    | '/api/mobile/app-updates'
    | '/api/mobile/commissions'
    | '/api/mobile/customers'
    | '/api/mobile/notifications'
    | '/api/mobile/packages'
    | '/api/mobile/payment-notifications'
    | '/api/mobile/payments'
    | '/api/mobile/search'
    | '/api/mobile/settings'
    | '/api/mobile/uploads'
    | '/api/public/archive-expired-records'
    | '/api/public/daraja-callback'
    | '/api/mobile/admin/audit'
    | '/api/mobile/admin/employees'
    | '/api/mobile/auth/me'
    | '/api/mobile/commissions/$id'
    | '/api/mobile/customers/$id'
    | '/api/mobile/customers/verify'
    | '/api/mobile/packages/$id'
    | '/api/mobile/packages/cleared'
    | '/api/mobile/packages/scan'
    | '/api/mobile/payment-notifications/$id'
    | '/api/mobile/payment-notifications/audit'
    | '/api/mobile/payments/$id'
    | '/api/mobile/payments/manual'
    | '/api/mobile/push/register'
    | '/api/mobile/stats/dashboard'
    | '/api/mobile/stats/home'
    | '/api/admin/users/$id/roles'
    | '/api/mobile/admin/employees/$id'
    | '/api/mobile/packages/$id/collect'
    | '/api/mobile/packages/$id/transition'
    | '/api/mobile/payment-notifications/$id/link'
    | '/api/mobile/admin/employees/$id/activity'
    | '/api/mobile/admin/employees/$id/reset-password'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/ops'
    | '/api/admin/users'
    | '/api/mobile/app-updates'
    | '/api/mobile/commissions'
    | '/api/mobile/customers'
    | '/api/mobile/notifications'
    | '/api/mobile/packages'
    | '/api/mobile/payment-notifications'
    | '/api/mobile/payments'
    | '/api/mobile/search'
    | '/api/mobile/settings'
    | '/api/mobile/uploads'
    | '/api/public/archive-expired-records'
    | '/api/public/daraja-callback'
    | '/api/mobile/admin/audit'
    | '/api/mobile/admin/employees'
    | '/api/mobile/auth/me'
    | '/api/mobile/commissions/$id'
    | '/api/mobile/customers/$id'
    | '/api/mobile/customers/verify'
    | '/api/mobile/packages/$id'
    | '/api/mobile/packages/cleared'
    | '/api/mobile/packages/scan'
    | '/api/mobile/payment-notifications/$id'
    | '/api/mobile/payment-notifications/audit'
    | '/api/mobile/payments/$id'
    | '/api/mobile/payments/manual'
    | '/api/mobile/push/register'
    | '/api/mobile/stats/dashboard'
    | '/api/mobile/stats/home'
    | '/api/admin/users/$id/roles'
    | '/api/mobile/admin/employees/$id'
    | '/api/mobile/packages/$id/collect'
    | '/api/mobile/packages/$id/transition'
    | '/api/mobile/payment-notifications/$id/link'
    | '/api/mobile/admin/employees/$id/activity'
    | '/api/mobile/admin/employees/$id/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  OpsRoute: typeof OpsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRouteWithChildren
  ApiMobileAppUpdatesRoute: typeof ApiMobileAppUpdatesRoute
  ApiMobileCommissionsRoute: typeof ApiMobileCommissionsRouteWithChildren
  ApiMobileCustomersRoute: typeof ApiMobileCustomersRouteWithChildren
  ApiMobileNotificationsRoute: typeof ApiMobileNotificationsRoute
  ApiMobilePackagesRoute: typeof ApiMobilePackagesRouteWithChildren
  ApiMobilePaymentNotificationsRoute: typeof ApiMobilePaymentNotificationsRouteWithChildren
  ApiMobilePaymentsRoute: typeof ApiMobilePaymentsRouteWithChildren
  ApiMobileSearchRoute: typeof ApiMobileSearchRoute
  ApiMobileSettingsRoute: typeof ApiMobileSettingsRoute
  ApiMobileUploadsRoute: typeof ApiMobileUploadsRoute
  ApiPublicArchiveExpiredRecordsRoute: typeof ApiPublicArchiveExpiredRecordsRoute
  ApiPublicDarajaCallbackRoute: typeof ApiPublicDarajaCallbackRoute
  ApiMobileAdminAuditRoute: typeof ApiMobileAdminAuditRoute
  ApiMobileAdminEmployeesRoute: typeof ApiMobileAdminEmployeesRouteWithChildren
  ApiMobileAuthMeRoute: typeof ApiMobileAuthMeRoute
  ApiMobilePushRegisterRoute: typeof ApiMobilePushRegisterRoute
  ApiMobileStatsDashboardRoute: typeof ApiMobileStatsDashboardRoute
  ApiMobileStatsHomeRoute: typeof ApiMobileStatsHomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daraja-callback': {
      id: '/api/public/daraja-callback'
      path: '/api/public/daraja-callback'
      fullPath: '/api/public/daraja-callback'
      preLoaderRoute: typeof ApiPublicDarajaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/archive-expired-records': {
      id: '/api/public/archive-expired-records'
      path: '/api/public/archive-expired-records'
      fullPath: '/api/public/archive-expired-records'
      preLoaderRoute: typeof ApiPublicArchiveExpiredRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/uploads': {
      id: '/api/mobile/uploads'
      path: '/api/mobile/uploads'
      fullPath: '/api/mobile/uploads'
      preLoaderRoute: typeof ApiMobileUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/settings': {
      id: '/api/mobile/settings'
      path: '/api/mobile/settings'
      fullPath: '/api/mobile/settings'
      preLoaderRoute: typeof ApiMobileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/search': {
      id: '/api/mobile/search'
      path: '/api/mobile/search'
      fullPath: '/api/mobile/search'
      preLoaderRoute: typeof ApiMobileSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/payments': {
      id: '/api/mobile/payments'
      path: '/api/mobile/payments'
      fullPath: '/api/mobile/payments'
      preLoaderRoute: typeof ApiMobilePaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/payment-notifications': {
      id: '/api/mobile/payment-notifications'
      path: '/api/mobile/payment-notifications'
      fullPath: '/api/mobile/payment-notifications'
      preLoaderRoute: typeof ApiMobilePaymentNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/packages': {
      id: '/api/mobile/packages'
      path: '/api/mobile/packages'
      fullPath: '/api/mobile/packages'
      preLoaderRoute: typeof ApiMobilePackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/notifications': {
      id: '/api/mobile/notifications'
      path: '/api/mobile/notifications'
      fullPath: '/api/mobile/notifications'
      preLoaderRoute: typeof ApiMobileNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/customers': {
      id: '/api/mobile/customers'
      path: '/api/mobile/customers'
      fullPath: '/api/mobile/customers'
      preLoaderRoute: typeof ApiMobileCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/commissions': {
      id: '/api/mobile/commissions'
      path: '/api/mobile/commissions'
      fullPath: '/api/mobile/commissions'
      preLoaderRoute: typeof ApiMobileCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/app-updates': {
      id: '/api/mobile/app-updates'
      path: '/api/mobile/app-updates'
      fullPath: '/api/mobile/app-updates'
      preLoaderRoute: typeof ApiMobileAppUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/stats/home': {
      id: '/api/mobile/stats/home'
      path: '/api/mobile/stats/home'
      fullPath: '/api/mobile/stats/home'
      preLoaderRoute: typeof ApiMobileStatsHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/stats/dashboard': {
      id: '/api/mobile/stats/dashboard'
      path: '/api/mobile/stats/dashboard'
      fullPath: '/api/mobile/stats/dashboard'
      preLoaderRoute: typeof ApiMobileStatsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/push/register': {
      id: '/api/mobile/push/register'
      path: '/api/mobile/push/register'
      fullPath: '/api/mobile/push/register'
      preLoaderRoute: typeof ApiMobilePushRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/payments/manual': {
      id: '/api/mobile/payments/manual'
      path: '/manual'
      fullPath: '/api/mobile/payments/manual'
      preLoaderRoute: typeof ApiMobilePaymentsManualRouteImport
      parentRoute: typeof ApiMobilePaymentsRoute
    }
    '/api/mobile/payments/$id': {
      id: '/api/mobile/payments/$id'
      path: '/$id'
      fullPath: '/api/mobile/payments/$id'
      preLoaderRoute: typeof ApiMobilePaymentsIdRouteImport
      parentRoute: typeof ApiMobilePaymentsRoute
    }
    '/api/mobile/payment-notifications/audit': {
      id: '/api/mobile/payment-notifications/audit'
      path: '/audit'
      fullPath: '/api/mobile/payment-notifications/audit'
      preLoaderRoute: typeof ApiMobilePaymentNotificationsAuditRouteImport
      parentRoute: typeof ApiMobilePaymentNotificationsRoute
    }
    '/api/mobile/payment-notifications/$id': {
      id: '/api/mobile/payment-notifications/$id'
      path: '/$id'
      fullPath: '/api/mobile/payment-notifications/$id'
      preLoaderRoute: typeof ApiMobilePaymentNotificationsIdRouteImport
      parentRoute: typeof ApiMobilePaymentNotificationsRoute
    }
    '/api/mobile/packages/scan': {
      id: '/api/mobile/packages/scan'
      path: '/scan'
      fullPath: '/api/mobile/packages/scan'
      preLoaderRoute: typeof ApiMobilePackagesScanRouteImport
      parentRoute: typeof ApiMobilePackagesRoute
    }
    '/api/mobile/packages/cleared': {
      id: '/api/mobile/packages/cleared'
      path: '/cleared'
      fullPath: '/api/mobile/packages/cleared'
      preLoaderRoute: typeof ApiMobilePackagesClearedRouteImport
      parentRoute: typeof ApiMobilePackagesRoute
    }
    '/api/mobile/packages/$id': {
      id: '/api/mobile/packages/$id'
      path: '/$id'
      fullPath: '/api/mobile/packages/$id'
      preLoaderRoute: typeof ApiMobilePackagesIdRouteImport
      parentRoute: typeof ApiMobilePackagesRoute
    }
    '/api/mobile/customers/verify': {
      id: '/api/mobile/customers/verify'
      path: '/verify'
      fullPath: '/api/mobile/customers/verify'
      preLoaderRoute: typeof ApiMobileCustomersVerifyRouteImport
      parentRoute: typeof ApiMobileCustomersRoute
    }
    '/api/mobile/customers/$id': {
      id: '/api/mobile/customers/$id'
      path: '/$id'
      fullPath: '/api/mobile/customers/$id'
      preLoaderRoute: typeof ApiMobileCustomersIdRouteImport
      parentRoute: typeof ApiMobileCustomersRoute
    }
    '/api/mobile/commissions/$id': {
      id: '/api/mobile/commissions/$id'
      path: '/$id'
      fullPath: '/api/mobile/commissions/$id'
      preLoaderRoute: typeof ApiMobileCommissionsIdRouteImport
      parentRoute: typeof ApiMobileCommissionsRoute
    }
    '/api/mobile/auth/me': {
      id: '/api/mobile/auth/me'
      path: '/api/mobile/auth/me'
      fullPath: '/api/mobile/auth/me'
      preLoaderRoute: typeof ApiMobileAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/admin/employees': {
      id: '/api/mobile/admin/employees'
      path: '/api/mobile/admin/employees'
      fullPath: '/api/mobile/admin/employees'
      preLoaderRoute: typeof ApiMobileAdminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/admin/audit': {
      id: '/api/mobile/admin/audit'
      path: '/api/mobile/admin/audit'
      fullPath: '/api/mobile/admin/audit'
      preLoaderRoute: typeof ApiMobileAdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/payment-notifications/$id/link': {
      id: '/api/mobile/payment-notifications/$id/link'
      path: '/link'
      fullPath: '/api/mobile/payment-notifications/$id/link'
      preLoaderRoute: typeof ApiMobilePaymentNotificationsIdLinkRouteImport
      parentRoute: typeof ApiMobilePaymentNotificationsIdRoute
    }
    '/api/mobile/packages/$id/transition': {
      id: '/api/mobile/packages/$id/transition'
      path: '/transition'
      fullPath: '/api/mobile/packages/$id/transition'
      preLoaderRoute: typeof ApiMobilePackagesIdTransitionRouteImport
      parentRoute: typeof ApiMobilePackagesIdRoute
    }
    '/api/mobile/packages/$id/collect': {
      id: '/api/mobile/packages/$id/collect'
      path: '/collect'
      fullPath: '/api/mobile/packages/$id/collect'
      preLoaderRoute: typeof ApiMobilePackagesIdCollectRouteImport
      parentRoute: typeof ApiMobilePackagesIdRoute
    }
    '/api/mobile/admin/employees/$id': {
      id: '/api/mobile/admin/employees/$id'
      path: '/$id'
      fullPath: '/api/mobile/admin/employees/$id'
      preLoaderRoute: typeof ApiMobileAdminEmployeesIdRouteImport
      parentRoute: typeof ApiMobileAdminEmployeesRoute
    }
    '/api/admin/users/$id/roles': {
      id: '/api/admin/users/$id/roles'
      path: '/$id/roles'
      fullPath: '/api/admin/users/$id/roles'
      preLoaderRoute: typeof ApiAdminUsersIdRolesRouteImport
      parentRoute: typeof ApiAdminUsersRoute
    }
    '/api/mobile/admin/employees/$id/reset-password': {
      id: '/api/mobile/admin/employees/$id/reset-password'
      path: '/reset-password'
      fullPath: '/api/mobile/admin/employees/$id/reset-password'
      preLoaderRoute: typeof ApiMobileAdminEmployeesIdResetPasswordRouteImport
      parentRoute: typeof ApiMobileAdminEmployeesIdRoute
    }
    '/api/mobile/admin/employees/$id/activity': {
      id: '/api/mobile/admin/employees/$id/activity'
      path: '/activity'
      fullPath: '/api/mobile/admin/employees/$id/activity'
      preLoaderRoute: typeof ApiMobileAdminEmployeesIdActivityRouteImport
      parentRoute: typeof ApiMobileAdminEmployeesIdRoute
    }
  }
}

interface ApiAdminUsersRouteChildren {
  ApiAdminUsersIdRolesRoute: typeof ApiAdminUsersIdRolesRoute
}

const ApiAdminUsersRouteChildren: ApiAdminUsersRouteChildren = {
  ApiAdminUsersIdRolesRoute: ApiAdminUsersIdRolesRoute,
}

const ApiAdminUsersRouteWithChildren = ApiAdminUsersRoute._addFileChildren(
  ApiAdminUsersRouteChildren,
)

interface ApiMobileCommissionsRouteChildren {
  ApiMobileCommissionsIdRoute: typeof ApiMobileCommissionsIdRoute
}

const ApiMobileCommissionsRouteChildren: ApiMobileCommissionsRouteChildren = {
  ApiMobileCommissionsIdRoute: ApiMobileCommissionsIdRoute,
}

const ApiMobileCommissionsRouteWithChildren =
  ApiMobileCommissionsRoute._addFileChildren(ApiMobileCommissionsRouteChildren)

interface ApiMobileCustomersRouteChildren {
  ApiMobileCustomersIdRoute: typeof ApiMobileCustomersIdRoute
  ApiMobileCustomersVerifyRoute: typeof ApiMobileCustomersVerifyRoute
}

const ApiMobileCustomersRouteChildren: ApiMobileCustomersRouteChildren = {
  ApiMobileCustomersIdRoute: ApiMobileCustomersIdRoute,
  ApiMobileCustomersVerifyRoute: ApiMobileCustomersVerifyRoute,
}

const ApiMobileCustomersRouteWithChildren =
  ApiMobileCustomersRoute._addFileChildren(ApiMobileCustomersRouteChildren)

interface ApiMobilePackagesIdRouteChildren {
  ApiMobilePackagesIdCollectRoute: typeof ApiMobilePackagesIdCollectRoute
  ApiMobilePackagesIdTransitionRoute: typeof ApiMobilePackagesIdTransitionRoute
}

const ApiMobilePackagesIdRouteChildren: ApiMobilePackagesIdRouteChildren = {
  ApiMobilePackagesIdCollectRoute: ApiMobilePackagesIdCollectRoute,
  ApiMobilePackagesIdTransitionRoute: ApiMobilePackagesIdTransitionRoute,
}

const ApiMobilePackagesIdRouteWithChildren =
  ApiMobilePackagesIdRoute._addFileChildren(ApiMobilePackagesIdRouteChildren)

interface ApiMobilePackagesRouteChildren {
  ApiMobilePackagesIdRoute: typeof ApiMobilePackagesIdRouteWithChildren
  ApiMobilePackagesClearedRoute: typeof ApiMobilePackagesClearedRoute
  ApiMobilePackagesScanRoute: typeof ApiMobilePackagesScanRoute
}

const ApiMobilePackagesRouteChildren: ApiMobilePackagesRouteChildren = {
  ApiMobilePackagesIdRoute: ApiMobilePackagesIdRouteWithChildren,
  ApiMobilePackagesClearedRoute: ApiMobilePackagesClearedRoute,
  ApiMobilePackagesScanRoute: ApiMobilePackagesScanRoute,
}

const ApiMobilePackagesRouteWithChildren =
  ApiMobilePackagesRoute._addFileChildren(ApiMobilePackagesRouteChildren)

interface ApiMobilePaymentNotificationsIdRouteChildren {
  ApiMobilePaymentNotificationsIdLinkRoute: typeof ApiMobilePaymentNotificationsIdLinkRoute
}

const ApiMobilePaymentNotificationsIdRouteChildren: ApiMobilePaymentNotificationsIdRouteChildren =
  {
    ApiMobilePaymentNotificationsIdLinkRoute:
      ApiMobilePaymentNotificationsIdLinkRoute,
  }

const ApiMobilePaymentNotificationsIdRouteWithChildren =
  ApiMobilePaymentNotificationsIdRoute._addFileChildren(
    ApiMobilePaymentNotificationsIdRouteChildren,
  )

interface ApiMobilePaymentNotificationsRouteChildren {
  ApiMobilePaymentNotificationsIdRoute: typeof ApiMobilePaymentNotificationsIdRouteWithChildren
  ApiMobilePaymentNotificationsAuditRoute: typeof ApiMobilePaymentNotificationsAuditRoute
}

const ApiMobilePaymentNotificationsRouteChildren: ApiMobilePaymentNotificationsRouteChildren =
  {
    ApiMobilePaymentNotificationsIdRoute:
      ApiMobilePaymentNotificationsIdRouteWithChildren,
    ApiMobilePaymentNotificationsAuditRoute:
      ApiMobilePaymentNotificationsAuditRoute,
  }

const ApiMobilePaymentNotificationsRouteWithChildren =
  ApiMobilePaymentNotificationsRoute._addFileChildren(
    ApiMobilePaymentNotificationsRouteChildren,
  )

interface ApiMobilePaymentsRouteChildren {
  ApiMobilePaymentsIdRoute: typeof ApiMobilePaymentsIdRoute
  ApiMobilePaymentsManualRoute: typeof ApiMobilePaymentsManualRoute
}

const ApiMobilePaymentsRouteChildren: ApiMobilePaymentsRouteChildren = {
  ApiMobilePaymentsIdRoute: ApiMobilePaymentsIdRoute,
  ApiMobilePaymentsManualRoute: ApiMobilePaymentsManualRoute,
}

const ApiMobilePaymentsRouteWithChildren =
  ApiMobilePaymentsRoute._addFileChildren(ApiMobilePaymentsRouteChildren)

interface ApiMobileAdminEmployeesIdRouteChildren {
  ApiMobileAdminEmployeesIdActivityRoute: typeof ApiMobileAdminEmployeesIdActivityRoute
  ApiMobileAdminEmployeesIdResetPasswordRoute: typeof ApiMobileAdminEmployeesIdResetPasswordRoute
}

const ApiMobileAdminEmployeesIdRouteChildren: ApiMobileAdminEmployeesIdRouteChildren =
  {
    ApiMobileAdminEmployeesIdActivityRoute:
      ApiMobileAdminEmployeesIdActivityRoute,
    ApiMobileAdminEmployeesIdResetPasswordRoute:
      ApiMobileAdminEmployeesIdResetPasswordRoute,
  }

const ApiMobileAdminEmployeesIdRouteWithChildren =
  ApiMobileAdminEmployeesIdRoute._addFileChildren(
    ApiMobileAdminEmployeesIdRouteChildren,
  )

interface ApiMobileAdminEmployeesRouteChildren {
  ApiMobileAdminEmployeesIdRoute: typeof ApiMobileAdminEmployeesIdRouteWithChildren
}

const ApiMobileAdminEmployeesRouteChildren: ApiMobileAdminEmployeesRouteChildren =
  {
    ApiMobileAdminEmployeesIdRoute: ApiMobileAdminEmployeesIdRouteWithChildren,
  }

const ApiMobileAdminEmployeesRouteWithChildren =
  ApiMobileAdminEmployeesRoute._addFileChildren(
    ApiMobileAdminEmployeesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  OpsRoute: OpsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRouteWithChildren,
  ApiMobileAppUpdatesRoute: ApiMobileAppUpdatesRoute,
  ApiMobileCommissionsRoute: ApiMobileCommissionsRouteWithChildren,
  ApiMobileCustomersRoute: ApiMobileCustomersRouteWithChildren,
  ApiMobileNotificationsRoute: ApiMobileNotificationsRoute,
  ApiMobilePackagesRoute: ApiMobilePackagesRouteWithChildren,
  ApiMobilePaymentNotificationsRoute:
    ApiMobilePaymentNotificationsRouteWithChildren,
  ApiMobilePaymentsRoute: ApiMobilePaymentsRouteWithChildren,
  ApiMobileSearchRoute: ApiMobileSearchRoute,
  ApiMobileSettingsRoute: ApiMobileSettingsRoute,
  ApiMobileUploadsRoute: ApiMobileUploadsRoute,
  ApiPublicArchiveExpiredRecordsRoute: ApiPublicArchiveExpiredRecordsRoute,
  ApiPublicDarajaCallbackRoute: ApiPublicDarajaCallbackRoute,
  ApiMobileAdminAuditRoute: ApiMobileAdminAuditRoute,
  ApiMobileAdminEmployeesRoute: ApiMobileAdminEmployeesRouteWithChildren,
  ApiMobileAuthMeRoute: ApiMobileAuthMeRoute,
  ApiMobilePushRegisterRoute: ApiMobilePushRegisterRoute,
  ApiMobileStatsDashboardRoute: ApiMobileStatsDashboardRoute,
  ApiMobileStatsHomeRoute: ApiMobileStatsHomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
