/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardRatesRouteImport } from './routes/dashboard.rates'
import { Route as DashboardPackagesRouteImport } from './routes/dashboard.packages'
import { Route as DashboardMarketingRouteImport } from './routes/dashboard.marketing'
import { Route as DashboardConversationsRouteImport } from './routes/dashboard.conversations'
import { Route as DashboardClientsRouteImport } from './routes/dashboard.clients'
import { Route as ApiPublicPublishScheduledRouteImport } from './routes/api/public/publish-scheduled'
import { Route as ApiPublicEvolutionWebhookRouteImport } from './routes/api/public/evolution-webhook'
import { Route as ApiPublicDarajaCallbackRouteImport } from './routes/api/public/daraja-callback'
import { Route as ApiMobileUploadsRouteImport } from './routes/api/mobile/uploads'
import { Route as ApiMobileStatsRouteImport } from './routes/api/mobile/stats'
import { Route as ApiMobileRatesRouteImport } from './routes/api/mobile/rates'
import { Route as ApiMobileQuoteRouteImport } from './routes/api/mobile/quote'
import { Route as ApiMobilePaymentsRouteImport } from './routes/api/mobile/payments'
import { Route as ApiMobilePackagesRouteImport } from './routes/api/mobile/packages'
import { Route as ApiMobileMarketingRouteImport } from './routes/api/mobile/marketing'
import { Route as ApiMobileConversationsRouteImport } from './routes/api/mobile/conversations'
import { Route as ApiMobileClientsRouteImport } from './routes/api/mobile/clients'
import { Route as ApiMobileRatesIdRouteImport } from './routes/api/mobile/rates.$id'
import { Route as ApiMobilePaymentsIdRouteImport } from './routes/api/mobile/payments.$id'
import { Route as ApiMobilePackagesIdRouteImport } from './routes/api/mobile/packages.$id'
import { Route as ApiMobileMarketingIdRouteImport } from './routes/api/mobile/marketing.$id'
import { Route as ApiMobileConversationsIdRouteImport } from './routes/api/mobile/conversations.$id'
import { Route as ApiMobileClientsIdRouteImport } from './routes/api/mobile/clients.$id'
import { Route as ApiMobileAuthMeRouteImport } from './routes/api/mobile/auth.me'
import { Route as ApiMobilePackagesIdEventsRouteImport } from './routes/api/mobile/packages.$id.events'
import { Route as ApiMobileConversationsIdMessagesRouteImport } from './routes/api/mobile/conversations.$id.messages'

const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRatesRoute = DashboardRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPackagesRoute = DashboardPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketingRoute = DashboardMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConversationsRoute = DashboardConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicPublishScheduledRoute =
  ApiPublicPublishScheduledRouteImport.update({
    id: '/api/public/publish-scheduled',
    path: '/api/public/publish-scheduled',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEvolutionWebhookRoute =
  ApiPublicEvolutionWebhookRouteImport.update({
    id: '/api/public/evolution-webhook',
    path: '/api/public/evolution-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDarajaCallbackRoute = ApiPublicDarajaCallbackRouteImport.update({
  id: '/api/public/daraja-callback',
  path: '/api/public/daraja-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileUploadsRoute = ApiMobileUploadsRouteImport.update({
  id: '/api/mobile/uploads',
  path: '/api/mobile/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileStatsRoute = ApiMobileStatsRouteImport.update({
  id: '/api/mobile/stats',
  path: '/api/mobile/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileRatesRoute = ApiMobileRatesRouteImport.update({
  id: '/api/mobile/rates',
  path: '/api/mobile/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileQuoteRoute = ApiMobileQuoteRouteImport.update({
  id: '/api/mobile/quote',
  path: '/api/mobile/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobilePaymentsRoute = ApiMobilePaymentsRouteImport.update({
  id: '/api/mobile/payments',
  path: '/api/mobile/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobilePackagesRoute = ApiMobilePackagesRouteImport.update({
  id: '/api/mobile/packages',
  path: '/api/mobile/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileMarketingRoute = ApiMobileMarketingRouteImport.update({
  id: '/api/mobile/marketing',
  path: '/api/mobile/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileConversationsRoute = ApiMobileConversationsRouteImport.update({
  id: '/api/mobile/conversations',
  path: '/api/mobile/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileClientsRoute = ApiMobileClientsRouteImport.update({
  id: '/api/mobile/clients',
  path: '/api/mobile/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileRatesIdRoute = ApiMobileRatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMobileRatesRoute,
} as any)
const ApiMobilePaymentsIdRoute = ApiMobilePaymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMobilePaymentsRoute,
} as any)
const ApiMobilePackagesIdRoute = ApiMobilePackagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMobilePackagesRoute,
} as any)
const ApiMobileMarketingIdRoute = ApiMobileMarketingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMobileMarketingRoute,
} as any)
const ApiMobileConversationsIdRoute =
  ApiMobileConversationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiMobileConversationsRoute,
  } as any)
const ApiMobileClientsIdRoute = ApiMobileClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMobileClientsRoute,
} as any)
const ApiMobileAuthMeRoute = ApiMobileAuthMeRouteImport.update({
  id: '/api/mobile/auth/me',
  path: '/api/mobile/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobilePackagesIdEventsRoute =
  ApiMobilePackagesIdEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => ApiMobilePackagesIdRoute,
  } as any)
const ApiMobileConversationsIdMessagesRoute =
  ApiMobileConversationsIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => ApiMobileConversationsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/quote': typeof QuoteRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/packages': typeof DashboardPackagesRoute
  '/dashboard/rates': typeof DashboardRatesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/mobile/clients': typeof ApiMobileClientsRouteWithChildren
  '/api/mobile/conversations': typeof ApiMobileConversationsRouteWithChildren
  '/api/mobile/marketing': typeof ApiMobileMarketingRouteWithChildren
  '/api/mobile/packages': typeof ApiMobilePackagesRouteWithChildren
  '/api/mobile/payments': typeof ApiMobilePaymentsRouteWithChildren
  '/api/mobile/quote': typeof ApiMobileQuoteRoute
  '/api/mobile/rates': typeof ApiMobileRatesRouteWithChildren
  '/api/mobile/stats': typeof ApiMobileStatsRoute
  '/api/mobile/uploads': typeof ApiMobileUploadsRoute
  '/api/public/daraja-callback': typeof ApiPublicDarajaCallbackRoute
  '/api/public/evolution-webhook': typeof ApiPublicEvolutionWebhookRoute
  '/api/public/publish-scheduled': typeof ApiPublicPublishScheduledRoute
  '/api/mobile/auth/me': typeof ApiMobileAuthMeRoute
  '/api/mobile/clients/$id': typeof ApiMobileClientsIdRoute
  '/api/mobile/conversations/$id': typeof ApiMobileConversationsIdRouteWithChildren
  '/api/mobile/marketing/$id': typeof ApiMobileMarketingIdRoute
  '/api/mobile/packages/$id': typeof ApiMobilePackagesIdRouteWithChildren
  '/api/mobile/payments/$id': typeof ApiMobilePaymentsIdRoute
  '/api/mobile/rates/$id': typeof ApiMobileRatesIdRoute
  '/api/mobile/conversations/$id/messages': typeof ApiMobileConversationsIdMessagesRoute
  '/api/mobile/packages/$id/events': typeof ApiMobilePackagesIdEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/quote': typeof QuoteRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/packages': typeof DashboardPackagesRoute
  '/dashboard/rates': typeof DashboardRatesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/mobile/clients': typeof ApiMobileClientsRouteWithChildren
  '/api/mobile/conversations': typeof ApiMobileConversationsRouteWithChildren
  '/api/mobile/marketing': typeof ApiMobileMarketingRouteWithChildren
  '/api/mobile/packages': typeof ApiMobilePackagesRouteWithChildren
  '/api/mobile/payments': typeof ApiMobilePaymentsRouteWithChildren
  '/api/mobile/quote': typeof ApiMobileQuoteRoute
  '/api/mobile/rates': typeof ApiMobileRatesRouteWithChildren
  '/api/mobile/stats': typeof ApiMobileStatsRoute
  '/api/mobile/uploads': typeof ApiMobileUploadsRoute
  '/api/public/daraja-callback': typeof ApiPublicDarajaCallbackRoute
  '/api/public/evolution-webhook': typeof ApiPublicEvolutionWebhookRoute
  '/api/public/publish-scheduled': typeof ApiPublicPublishScheduledRoute
  '/api/mobile/auth/me': typeof ApiMobileAuthMeRoute
  '/api/mobile/clients/$id': typeof ApiMobileClientsIdRoute
  '/api/mobile/conversations/$id': typeof ApiMobileConversationsIdRouteWithChildren
  '/api/mobile/marketing/$id': typeof ApiMobileMarketingIdRoute
  '/api/mobile/packages/$id': typeof ApiMobilePackagesIdRouteWithChildren
  '/api/mobile/payments/$id': typeof ApiMobilePaymentsIdRoute
  '/api/mobile/rates/$id': typeof ApiMobileRatesIdRoute
  '/api/mobile/conversations/$id/messages': typeof ApiMobileConversationsIdMessagesRoute
  '/api/mobile/packages/$id/events': typeof ApiMobilePackagesIdEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/quote': typeof QuoteRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/packages': typeof DashboardPackagesRoute
  '/dashboard/rates': typeof DashboardRatesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/mobile/clients': typeof ApiMobileClientsRouteWithChildren
  '/api/mobile/conversations': typeof ApiMobileConversationsRouteWithChildren
  '/api/mobile/marketing': typeof ApiMobileMarketingRouteWithChildren
  '/api/mobile/packages': typeof ApiMobilePackagesRouteWithChildren
  '/api/mobile/payments': typeof ApiMobilePaymentsRouteWithChildren
  '/api/mobile/quote': typeof ApiMobileQuoteRoute
  '/api/mobile/rates': typeof ApiMobileRatesRouteWithChildren
  '/api/mobile/stats': typeof ApiMobileStatsRoute
  '/api/mobile/uploads': typeof ApiMobileUploadsRoute
  '/api/public/daraja-callback': typeof ApiPublicDarajaCallbackRoute
  '/api/public/evolution-webhook': typeof ApiPublicEvolutionWebhookRoute
  '/api/public/publish-scheduled': typeof ApiPublicPublishScheduledRoute
  '/api/mobile/auth/me': typeof ApiMobileAuthMeRoute
  '/api/mobile/clients/$id': typeof ApiMobileClientsIdRoute
  '/api/mobile/conversations/$id': typeof ApiMobileConversationsIdRouteWithChildren
  '/api/mobile/marketing/$id': typeof ApiMobileMarketingIdRoute
  '/api/mobile/packages/$id': typeof ApiMobilePackagesIdRouteWithChildren
  '/api/mobile/payments/$id': typeof ApiMobilePaymentsIdRoute
  '/api/mobile/rates/$id': typeof ApiMobileRatesIdRoute
  '/api/mobile/conversations/$id/messages': typeof ApiMobileConversationsIdMessagesRoute
  '/api/mobile/packages/$id/events': typeof ApiMobilePackagesIdEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/quote'
    | '/dashboard/clients'
    | '/dashboard/conversations'
    | '/dashboard/marketing'
    | '/dashboard/packages'
    | '/dashboard/rates'
    | '/dashboard/'
    | '/api/mobile/clients'
    | '/api/mobile/conversations'
    | '/api/mobile/marketing'
    | '/api/mobile/packages'
    | '/api/mobile/payments'
    | '/api/mobile/quote'
    | '/api/mobile/rates'
    | '/api/mobile/stats'
    | '/api/mobile/uploads'
    | '/api/public/daraja-callback'
    | '/api/public/evolution-webhook'
    | '/api/public/publish-scheduled'
    | '/api/mobile/auth/me'
    | '/api/mobile/clients/$id'
    | '/api/mobile/conversations/$id'
    | '/api/mobile/marketing/$id'
    | '/api/mobile/packages/$id'
    | '/api/mobile/payments/$id'
    | '/api/mobile/rates/$id'
    | '/api/mobile/conversations/$id/messages'
    | '/api/mobile/packages/$id/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/quote'
    | '/dashboard/clients'
    | '/dashboard/conversations'
    | '/dashboard/marketing'
    | '/dashboard/packages'
    | '/dashboard/rates'
    | '/dashboard'
    | '/api/mobile/clients'
    | '/api/mobile/conversations'
    | '/api/mobile/marketing'
    | '/api/mobile/packages'
    | '/api/mobile/payments'
    | '/api/mobile/quote'
    | '/api/mobile/rates'
    | '/api/mobile/stats'
    | '/api/mobile/uploads'
    | '/api/public/daraja-callback'
    | '/api/public/evolution-webhook'
    | '/api/public/publish-scheduled'
    | '/api/mobile/auth/me'
    | '/api/mobile/clients/$id'
    | '/api/mobile/conversations/$id'
    | '/api/mobile/marketing/$id'
    | '/api/mobile/packages/$id'
    | '/api/mobile/payments/$id'
    | '/api/mobile/rates/$id'
    | '/api/mobile/conversations/$id/messages'
    | '/api/mobile/packages/$id/events'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/quote'
    | '/dashboard/clients'
    | '/dashboard/conversations'
    | '/dashboard/marketing'
    | '/dashboard/packages'
    | '/dashboard/rates'
    | '/dashboard/'
    | '/api/mobile/clients'
    | '/api/mobile/conversations'
    | '/api/mobile/marketing'
    | '/api/mobile/packages'
    | '/api/mobile/payments'
    | '/api/mobile/quote'
    | '/api/mobile/rates'
    | '/api/mobile/stats'
    | '/api/mobile/uploads'
    | '/api/public/daraja-callback'
    | '/api/public/evolution-webhook'
    | '/api/public/publish-scheduled'
    | '/api/mobile/auth/me'
    | '/api/mobile/clients/$id'
    | '/api/mobile/conversations/$id'
    | '/api/mobile/marketing/$id'
    | '/api/mobile/packages/$id'
    | '/api/mobile/payments/$id'
    | '/api/mobile/rates/$id'
    | '/api/mobile/conversations/$id/messages'
    | '/api/mobile/packages/$id/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  QuoteRoute: typeof QuoteRoute
  ApiMobileClientsRoute: typeof ApiMobileClientsRouteWithChildren
  ApiMobileConversationsRoute: typeof ApiMobileConversationsRouteWithChildren
  ApiMobileMarketingRoute: typeof ApiMobileMarketingRouteWithChildren
  ApiMobilePackagesRoute: typeof ApiMobilePackagesRouteWithChildren
  ApiMobilePaymentsRoute: typeof ApiMobilePaymentsRouteWithChildren
  ApiMobileQuoteRoute: typeof ApiMobileQuoteRoute
  ApiMobileRatesRoute: typeof ApiMobileRatesRouteWithChildren
  ApiMobileStatsRoute: typeof ApiMobileStatsRoute
  ApiMobileUploadsRoute: typeof ApiMobileUploadsRoute
  ApiPublicDarajaCallbackRoute: typeof ApiPublicDarajaCallbackRoute
  ApiPublicEvolutionWebhookRoute: typeof ApiPublicEvolutionWebhookRoute
  ApiPublicPublishScheduledRoute: typeof ApiPublicPublishScheduledRoute
  ApiMobileAuthMeRoute: typeof ApiMobileAuthMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rates': {
      id: '/dashboard/rates'
      path: '/rates'
      fullPath: '/dashboard/rates'
      preLoaderRoute: typeof DashboardRatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/packages': {
      id: '/dashboard/packages'
      path: '/packages'
      fullPath: '/dashboard/packages'
      preLoaderRoute: typeof DashboardPackagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/marketing': {
      id: '/dashboard/marketing'
      path: '/marketing'
      fullPath: '/dashboard/marketing'
      preLoaderRoute: typeof DashboardMarketingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/conversations': {
      id: '/dashboard/conversations'
      path: '/conversations'
      fullPath: '/dashboard/conversations'
      preLoaderRoute: typeof DashboardConversationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/publish-scheduled': {
      id: '/api/public/publish-scheduled'
      path: '/api/public/publish-scheduled'
      fullPath: '/api/public/publish-scheduled'
      preLoaderRoute: typeof ApiPublicPublishScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/evolution-webhook': {
      id: '/api/public/evolution-webhook'
      path: '/api/public/evolution-webhook'
      fullPath: '/api/public/evolution-webhook'
      preLoaderRoute: typeof ApiPublicEvolutionWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daraja-callback': {
      id: '/api/public/daraja-callback'
      path: '/api/public/daraja-callback'
      fullPath: '/api/public/daraja-callback'
      preLoaderRoute: typeof ApiPublicDarajaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/uploads': {
      id: '/api/mobile/uploads'
      path: '/api/mobile/uploads'
      fullPath: '/api/mobile/uploads'
      preLoaderRoute: typeof ApiMobileUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/stats': {
      id: '/api/mobile/stats'
      path: '/api/mobile/stats'
      fullPath: '/api/mobile/stats'
      preLoaderRoute: typeof ApiMobileStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/rates': {
      id: '/api/mobile/rates'
      path: '/api/mobile/rates'
      fullPath: '/api/mobile/rates'
      preLoaderRoute: typeof ApiMobileRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/quote': {
      id: '/api/mobile/quote'
      path: '/api/mobile/quote'
      fullPath: '/api/mobile/quote'
      preLoaderRoute: typeof ApiMobileQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/payments': {
      id: '/api/mobile/payments'
      path: '/api/mobile/payments'
      fullPath: '/api/mobile/payments'
      preLoaderRoute: typeof ApiMobilePaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/packages': {
      id: '/api/mobile/packages'
      path: '/api/mobile/packages'
      fullPath: '/api/mobile/packages'
      preLoaderRoute: typeof ApiMobilePackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/marketing': {
      id: '/api/mobile/marketing'
      path: '/api/mobile/marketing'
      fullPath: '/api/mobile/marketing'
      preLoaderRoute: typeof ApiMobileMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/conversations': {
      id: '/api/mobile/conversations'
      path: '/api/mobile/conversations'
      fullPath: '/api/mobile/conversations'
      preLoaderRoute: typeof ApiMobileConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/clients': {
      id: '/api/mobile/clients'
      path: '/api/mobile/clients'
      fullPath: '/api/mobile/clients'
      preLoaderRoute: typeof ApiMobileClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/rates/$id': {
      id: '/api/mobile/rates/$id'
      path: '/$id'
      fullPath: '/api/mobile/rates/$id'
      preLoaderRoute: typeof ApiMobileRatesIdRouteImport
      parentRoute: typeof ApiMobileRatesRoute
    }
    '/api/mobile/payments/$id': {
      id: '/api/mobile/payments/$id'
      path: '/$id'
      fullPath: '/api/mobile/payments/$id'
      preLoaderRoute: typeof ApiMobilePaymentsIdRouteImport
      parentRoute: typeof ApiMobilePaymentsRoute
    }
    '/api/mobile/packages/$id': {
      id: '/api/mobile/packages/$id'
      path: '/$id'
      fullPath: '/api/mobile/packages/$id'
      preLoaderRoute: typeof ApiMobilePackagesIdRouteImport
      parentRoute: typeof ApiMobilePackagesRoute
    }
    '/api/mobile/marketing/$id': {
      id: '/api/mobile/marketing/$id'
      path: '/$id'
      fullPath: '/api/mobile/marketing/$id'
      preLoaderRoute: typeof ApiMobileMarketingIdRouteImport
      parentRoute: typeof ApiMobileMarketingRoute
    }
    '/api/mobile/conversations/$id': {
      id: '/api/mobile/conversations/$id'
      path: '/$id'
      fullPath: '/api/mobile/conversations/$id'
      preLoaderRoute: typeof ApiMobileConversationsIdRouteImport
      parentRoute: typeof ApiMobileConversationsRoute
    }
    '/api/mobile/clients/$id': {
      id: '/api/mobile/clients/$id'
      path: '/$id'
      fullPath: '/api/mobile/clients/$id'
      preLoaderRoute: typeof ApiMobileClientsIdRouteImport
      parentRoute: typeof ApiMobileClientsRoute
    }
    '/api/mobile/auth/me': {
      id: '/api/mobile/auth/me'
      path: '/api/mobile/auth/me'
      fullPath: '/api/mobile/auth/me'
      preLoaderRoute: typeof ApiMobileAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/packages/$id/events': {
      id: '/api/mobile/packages/$id/events'
      path: '/events'
      fullPath: '/api/mobile/packages/$id/events'
      preLoaderRoute: typeof ApiMobilePackagesIdEventsRouteImport
      parentRoute: typeof ApiMobilePackagesIdRoute
    }
    '/api/mobile/conversations/$id/messages': {
      id: '/api/mobile/conversations/$id/messages'
      path: '/messages'
      fullPath: '/api/mobile/conversations/$id/messages'
      preLoaderRoute: typeof ApiMobileConversationsIdMessagesRouteImport
      parentRoute: typeof ApiMobileConversationsIdRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardConversationsRoute: typeof DashboardConversationsRoute
  DashboardMarketingRoute: typeof DashboardMarketingRoute
  DashboardPackagesRoute: typeof DashboardPackagesRoute
  DashboardRatesRoute: typeof DashboardRatesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardConversationsRoute: DashboardConversationsRoute,
  DashboardMarketingRoute: DashboardMarketingRoute,
  DashboardPackagesRoute: DashboardPackagesRoute,
  DashboardRatesRoute: DashboardRatesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiMobileClientsRouteChildren {
  ApiMobileClientsIdRoute: typeof ApiMobileClientsIdRoute
}

const ApiMobileClientsRouteChildren: ApiMobileClientsRouteChildren = {
  ApiMobileClientsIdRoute: ApiMobileClientsIdRoute,
}

const ApiMobileClientsRouteWithChildren =
  ApiMobileClientsRoute._addFileChildren(ApiMobileClientsRouteChildren)

interface ApiMobileConversationsIdRouteChildren {
  ApiMobileConversationsIdMessagesRoute: typeof ApiMobileConversationsIdMessagesRoute
}

const ApiMobileConversationsIdRouteChildren: ApiMobileConversationsIdRouteChildren =
  {
    ApiMobileConversationsIdMessagesRoute:
      ApiMobileConversationsIdMessagesRoute,
  }

const ApiMobileConversationsIdRouteWithChildren =
  ApiMobileConversationsIdRoute._addFileChildren(
    ApiMobileConversationsIdRouteChildren,
  )

interface ApiMobileConversationsRouteChildren {
  ApiMobileConversationsIdRoute: typeof ApiMobileConversationsIdRouteWithChildren
}

const ApiMobileConversationsRouteChildren: ApiMobileConversationsRouteChildren =
  {
    ApiMobileConversationsIdRoute: ApiMobileConversationsIdRouteWithChildren,
  }

const ApiMobileConversationsRouteWithChildren =
  ApiMobileConversationsRoute._addFileChildren(
    ApiMobileConversationsRouteChildren,
  )

interface ApiMobileMarketingRouteChildren {
  ApiMobileMarketingIdRoute: typeof ApiMobileMarketingIdRoute
}

const ApiMobileMarketingRouteChildren: ApiMobileMarketingRouteChildren = {
  ApiMobileMarketingIdRoute: ApiMobileMarketingIdRoute,
}

const ApiMobileMarketingRouteWithChildren =
  ApiMobileMarketingRoute._addFileChildren(ApiMobileMarketingRouteChildren)

interface ApiMobilePackagesIdRouteChildren {
  ApiMobilePackagesIdEventsRoute: typeof ApiMobilePackagesIdEventsRoute
}

const ApiMobilePackagesIdRouteChildren: ApiMobilePackagesIdRouteChildren = {
  ApiMobilePackagesIdEventsRoute: ApiMobilePackagesIdEventsRoute,
}

const ApiMobilePackagesIdRouteWithChildren =
  ApiMobilePackagesIdRoute._addFileChildren(ApiMobilePackagesIdRouteChildren)

interface ApiMobilePackagesRouteChildren {
  ApiMobilePackagesIdRoute: typeof ApiMobilePackagesIdRouteWithChildren
}

const ApiMobilePackagesRouteChildren: ApiMobilePackagesRouteChildren = {
  ApiMobilePackagesIdRoute: ApiMobilePackagesIdRouteWithChildren,
}

const ApiMobilePackagesRouteWithChildren =
  ApiMobilePackagesRoute._addFileChildren(ApiMobilePackagesRouteChildren)

interface ApiMobilePaymentsRouteChildren {
  ApiMobilePaymentsIdRoute: typeof ApiMobilePaymentsIdRoute
}

const ApiMobilePaymentsRouteChildren: ApiMobilePaymentsRouteChildren = {
  ApiMobilePaymentsIdRoute: ApiMobilePaymentsIdRoute,
}

const ApiMobilePaymentsRouteWithChildren =
  ApiMobilePaymentsRoute._addFileChildren(ApiMobilePaymentsRouteChildren)

interface ApiMobileRatesRouteChildren {
  ApiMobileRatesIdRoute: typeof ApiMobileRatesIdRoute
}

const ApiMobileRatesRouteChildren: ApiMobileRatesRouteChildren = {
  ApiMobileRatesIdRoute: ApiMobileRatesIdRoute,
}

const ApiMobileRatesRouteWithChildren = ApiMobileRatesRoute._addFileChildren(
  ApiMobileRatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  QuoteRoute: QuoteRoute,
  ApiMobileClientsRoute: ApiMobileClientsRouteWithChildren,
  ApiMobileConversationsRoute: ApiMobileConversationsRouteWithChildren,
  ApiMobileMarketingRoute: ApiMobileMarketingRouteWithChildren,
  ApiMobilePackagesRoute: ApiMobilePackagesRouteWithChildren,
  ApiMobilePaymentsRoute: ApiMobilePaymentsRouteWithChildren,
  ApiMobileQuoteRoute: ApiMobileQuoteRoute,
  ApiMobileRatesRoute: ApiMobileRatesRouteWithChildren,
  ApiMobileStatsRoute: ApiMobileStatsRoute,
  ApiMobileUploadsRoute: ApiMobileUploadsRoute,
  ApiPublicDarajaCallbackRoute: ApiPublicDarajaCallbackRoute,
  ApiPublicEvolutionWebhookRoute: ApiPublicEvolutionWebhookRoute,
  ApiPublicPublishScheduledRoute: ApiPublicPublishScheduledRoute,
  ApiMobileAuthMeRoute: ApiMobileAuthMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
