/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicArchiveExpiredRecordsRouteImport } from './routes/api/public/archive-expired-records'
import { Route as ApiMobileUploadsRouteImport } from './routes/api/mobile/uploads'
import { Route as ApiMobileSettingsRouteImport } from './routes/api/mobile/settings'
import { Route as ApiMobileNotificationsRouteImport } from './routes/api/mobile/notifications'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiMobilePushRegisterRouteImport } from './routes/api/mobile/push.register'
import { Route as ApiMobileAuthMeRouteImport } from './routes/api/mobile/auth.me'
import { Route as ApiMobileAdminEmployeesRouteImport } from './routes/api/mobile/admin/employees'
import { Route as ApiMobileAdminAuditRouteImport } from './routes/api/mobile/admin/audit'
import { Route as ApiMobileAdminEmployeesIdRouteImport } from './routes/api/mobile/admin/employees.$id'
import { Route as ApiAdminUsersIdRolesRouteImport } from './routes/api/admin/users.$id.roles'
import { Route as ApiMobileAdminEmployeesIdResetPasswordRouteImport } from './routes/api/mobile/admin/employees.$id.reset-password'
import { Route as ApiMobileAdminEmployeesIdActivityRouteImport } from './routes/api/mobile/admin/employees.$id.activity'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArchiveExpiredRecordsRoute =
  ApiPublicArchiveExpiredRecordsRouteImport.update({
    id: '/api/public/archive-expired-records',
    path: '/api/public/archive-expired-records',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileUploadsRoute = ApiMobileUploadsRouteImport.update({
  id: '/api/mobile/uploads',
  path: '/api/mobile/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileSettingsRoute = ApiMobileSettingsRouteImport.update({
  id: '/api/mobile/settings',
  path: '/api/mobile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileNotificationsRoute = ApiMobileNotificationsRouteImport.update({
  id: '/api/mobile/notifications',
  path: '/api/mobile/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobilePushRegisterRoute = ApiMobilePushRegisterRouteImport.update({
  id: '/api/mobile/push/register',
  path: '/api/mobile/push/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAuthMeRoute = ApiMobileAuthMeRouteImport.update({
  id: '/api/mobile/auth/me',
  path: '/api/mobile/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAdminEmployeesRoute = ApiMobileAdminEmployeesRouteImport.update({
  id: '/api/mobile/admin/employees',
  path: '/api/mobile/admin/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAdminAuditRoute = ApiMobileAdminAuditRouteImport.update({
  id: '/api/mobile/admin/audit',
  path: '/api/mobile/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAdminEmployeesIdRoute =
  ApiMobileAdminEmployeesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiMobileAdminEmployeesRoute,
  } as any)
const ApiAdminUsersIdRolesRoute = ApiAdminUsersIdRolesRouteImport.update({
  id: '/$id/roles',
  path: '/$id/roles',
  getParentRoute: () => ApiAdminUsersRoute,
} as any)
const ApiMobileAdminEmployeesIdResetPasswordRoute =
  ApiMobileAdminEmployeesIdResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => ApiMobileAdminEmployeesIdRoute,
  } as any)
const ApiMobileAdminEmployeesIdActivityRoute =
  ApiMobileAdminEmployeesIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => ApiMobileAdminEmployeesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/mobile/notifications': typeof ApiMobileNotificationsRoute
  '/api/mobile/settings': typeof ApiMobileSettingsRoute
  '/api/mobile/uploads': typeof ApiMobileUploadsRoute
  '/api/public/archive-expired-records': typeof ApiPublicArchiveExpiredRecordsRoute
  '/api/mobile/admin/audit': typeof ApiMobileAdminAuditRoute
  '/api/mobile/admin/employees': typeof ApiMobileAdminEmployeesRouteWithChildren
  '/api/mobile/auth/me': typeof ApiMobileAuthMeRoute
  '/api/mobile/push/register': typeof ApiMobilePushRegisterRoute
  '/api/admin/users/$id/roles': typeof ApiAdminUsersIdRolesRoute
  '/api/mobile/admin/employees/$id': typeof ApiMobileAdminEmployeesIdRouteWithChildren
  '/api/mobile/admin/employees/$id/activity': typeof ApiMobileAdminEmployeesIdActivityRoute
  '/api/mobile/admin/employees/$id/reset-password': typeof ApiMobileAdminEmployeesIdResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/mobile/notifications': typeof ApiMobileNotificationsRoute
  '/api/mobile/settings': typeof ApiMobileSettingsRoute
  '/api/mobile/uploads': typeof ApiMobileUploadsRoute
  '/api/public/archive-expired-records': typeof ApiPublicArchiveExpiredRecordsRoute
  '/api/mobile/admin/audit': typeof ApiMobileAdminAuditRoute
  '/api/mobile/admin/employees': typeof ApiMobileAdminEmployeesRouteWithChildren
  '/api/mobile/auth/me': typeof ApiMobileAuthMeRoute
  '/api/mobile/push/register': typeof ApiMobilePushRegisterRoute
  '/api/admin/users/$id/roles': typeof ApiAdminUsersIdRolesRoute
  '/api/mobile/admin/employees/$id': typeof ApiMobileAdminEmployeesIdRouteWithChildren
  '/api/mobile/admin/employees/$id/activity': typeof ApiMobileAdminEmployeesIdActivityRoute
  '/api/mobile/admin/employees/$id/reset-password': typeof ApiMobileAdminEmployeesIdResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/mobile/notifications': typeof ApiMobileNotificationsRoute
  '/api/mobile/settings': typeof ApiMobileSettingsRoute
  '/api/mobile/uploads': typeof ApiMobileUploadsRoute
  '/api/public/archive-expired-records': typeof ApiPublicArchiveExpiredRecordsRoute
  '/api/mobile/admin/audit': typeof ApiMobileAdminAuditRoute
  '/api/mobile/admin/employees': typeof ApiMobileAdminEmployeesRouteWithChildren
  '/api/mobile/auth/me': typeof ApiMobileAuthMeRoute
  '/api/mobile/push/register': typeof ApiMobilePushRegisterRoute
  '/api/admin/users/$id/roles': typeof ApiAdminUsersIdRolesRoute
  '/api/mobile/admin/employees/$id': typeof ApiMobileAdminEmployeesIdRouteWithChildren
  '/api/mobile/admin/employees/$id/activity': typeof ApiMobileAdminEmployeesIdActivityRoute
  '/api/mobile/admin/employees/$id/reset-password': typeof ApiMobileAdminEmployeesIdResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/admin/users'
    | '/api/mobile/notifications'
    | '/api/mobile/settings'
    | '/api/mobile/uploads'
    | '/api/public/archive-expired-records'
    | '/api/mobile/admin/audit'
    | '/api/mobile/admin/employees'
    | '/api/mobile/auth/me'
    | '/api/mobile/push/register'
    | '/api/admin/users/$id/roles'
    | '/api/mobile/admin/employees/$id'
    | '/api/mobile/admin/employees/$id/activity'
    | '/api/mobile/admin/employees/$id/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/admin/users'
    | '/api/mobile/notifications'
    | '/api/mobile/settings'
    | '/api/mobile/uploads'
    | '/api/public/archive-expired-records'
    | '/api/mobile/admin/audit'
    | '/api/mobile/admin/employees'
    | '/api/mobile/auth/me'
    | '/api/mobile/push/register'
    | '/api/admin/users/$id/roles'
    | '/api/mobile/admin/employees/$id'
    | '/api/mobile/admin/employees/$id/activity'
    | '/api/mobile/admin/employees/$id/reset-password'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/admin/users'
    | '/api/mobile/notifications'
    | '/api/mobile/settings'
    | '/api/mobile/uploads'
    | '/api/public/archive-expired-records'
    | '/api/mobile/admin/audit'
    | '/api/mobile/admin/employees'
    | '/api/mobile/auth/me'
    | '/api/mobile/push/register'
    | '/api/admin/users/$id/roles'
    | '/api/mobile/admin/employees/$id'
    | '/api/mobile/admin/employees/$id/activity'
    | '/api/mobile/admin/employees/$id/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRouteWithChildren
  ApiMobileNotificationsRoute: typeof ApiMobileNotificationsRoute
  ApiMobileSettingsRoute: typeof ApiMobileSettingsRoute
  ApiMobileUploadsRoute: typeof ApiMobileUploadsRoute
  ApiPublicArchiveExpiredRecordsRoute: typeof ApiPublicArchiveExpiredRecordsRoute
  ApiMobileAdminAuditRoute: typeof ApiMobileAdminAuditRoute
  ApiMobileAdminEmployeesRoute: typeof ApiMobileAdminEmployeesRouteWithChildren
  ApiMobileAuthMeRoute: typeof ApiMobileAuthMeRoute
  ApiMobilePushRegisterRoute: typeof ApiMobilePushRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/archive-expired-records': {
      id: '/api/public/archive-expired-records'
      path: '/api/public/archive-expired-records'
      fullPath: '/api/public/archive-expired-records'
      preLoaderRoute: typeof ApiPublicArchiveExpiredRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/uploads': {
      id: '/api/mobile/uploads'
      path: '/api/mobile/uploads'
      fullPath: '/api/mobile/uploads'
      preLoaderRoute: typeof ApiMobileUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/settings': {
      id: '/api/mobile/settings'
      path: '/api/mobile/settings'
      fullPath: '/api/mobile/settings'
      preLoaderRoute: typeof ApiMobileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/notifications': {
      id: '/api/mobile/notifications'
      path: '/api/mobile/notifications'
      fullPath: '/api/mobile/notifications'
      preLoaderRoute: typeof ApiMobileNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/push/register': {
      id: '/api/mobile/push/register'
      path: '/api/mobile/push/register'
      fullPath: '/api/mobile/push/register'
      preLoaderRoute: typeof ApiMobilePushRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/auth/me': {
      id: '/api/mobile/auth/me'
      path: '/api/mobile/auth/me'
      fullPath: '/api/mobile/auth/me'
      preLoaderRoute: typeof ApiMobileAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/admin/employees': {
      id: '/api/mobile/admin/employees'
      path: '/api/mobile/admin/employees'
      fullPath: '/api/mobile/admin/employees'
      preLoaderRoute: typeof ApiMobileAdminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/admin/audit': {
      id: '/api/mobile/admin/audit'
      path: '/api/mobile/admin/audit'
      fullPath: '/api/mobile/admin/audit'
      preLoaderRoute: typeof ApiMobileAdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/admin/employees/$id': {
      id: '/api/mobile/admin/employees/$id'
      path: '/$id'
      fullPath: '/api/mobile/admin/employees/$id'
      preLoaderRoute: typeof ApiMobileAdminEmployeesIdRouteImport
      parentRoute: typeof ApiMobileAdminEmployeesRoute
    }
    '/api/admin/users/$id/roles': {
      id: '/api/admin/users/$id/roles'
      path: '/$id/roles'
      fullPath: '/api/admin/users/$id/roles'
      preLoaderRoute: typeof ApiAdminUsersIdRolesRouteImport
      parentRoute: typeof ApiAdminUsersRoute
    }
    '/api/mobile/admin/employees/$id/reset-password': {
      id: '/api/mobile/admin/employees/$id/reset-password'
      path: '/reset-password'
      fullPath: '/api/mobile/admin/employees/$id/reset-password'
      preLoaderRoute: typeof ApiMobileAdminEmployeesIdResetPasswordRouteImport
      parentRoute: typeof ApiMobileAdminEmployeesIdRoute
    }
    '/api/mobile/admin/employees/$id/activity': {
      id: '/api/mobile/admin/employees/$id/activity'
      path: '/activity'
      fullPath: '/api/mobile/admin/employees/$id/activity'
      preLoaderRoute: typeof ApiMobileAdminEmployeesIdActivityRouteImport
      parentRoute: typeof ApiMobileAdminEmployeesIdRoute
    }
  }
}

interface ApiAdminUsersRouteChildren {
  ApiAdminUsersIdRolesRoute: typeof ApiAdminUsersIdRolesRoute
}

const ApiAdminUsersRouteChildren: ApiAdminUsersRouteChildren = {
  ApiAdminUsersIdRolesRoute: ApiAdminUsersIdRolesRoute,
}

const ApiAdminUsersRouteWithChildren = ApiAdminUsersRoute._addFileChildren(
  ApiAdminUsersRouteChildren,
)

interface ApiMobileAdminEmployeesIdRouteChildren {
  ApiMobileAdminEmployeesIdActivityRoute: typeof ApiMobileAdminEmployeesIdActivityRoute
  ApiMobileAdminEmployeesIdResetPasswordRoute: typeof ApiMobileAdminEmployeesIdResetPasswordRoute
}

const ApiMobileAdminEmployeesIdRouteChildren: ApiMobileAdminEmployeesIdRouteChildren =
  {
    ApiMobileAdminEmployeesIdActivityRoute:
      ApiMobileAdminEmployeesIdActivityRoute,
    ApiMobileAdminEmployeesIdResetPasswordRoute:
      ApiMobileAdminEmployeesIdResetPasswordRoute,
  }

const ApiMobileAdminEmployeesIdRouteWithChildren =
  ApiMobileAdminEmployeesIdRoute._addFileChildren(
    ApiMobileAdminEmployeesIdRouteChildren,
  )

interface ApiMobileAdminEmployeesRouteChildren {
  ApiMobileAdminEmployeesIdRoute: typeof ApiMobileAdminEmployeesIdRouteWithChildren
}

const ApiMobileAdminEmployeesRouteChildren: ApiMobileAdminEmployeesRouteChildren =
  {
    ApiMobileAdminEmployeesIdRoute: ApiMobileAdminEmployeesIdRouteWithChildren,
  }

const ApiMobileAdminEmployeesRouteWithChildren =
  ApiMobileAdminEmployeesRoute._addFileChildren(
    ApiMobileAdminEmployeesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiAdminUsersRoute: ApiAdminUsersRouteWithChildren,
  ApiMobileNotificationsRoute: ApiMobileNotificationsRoute,
  ApiMobileSettingsRoute: ApiMobileSettingsRoute,
  ApiMobileUploadsRoute: ApiMobileUploadsRoute,
  ApiPublicArchiveExpiredRecordsRoute: ApiPublicArchiveExpiredRecordsRoute,
  ApiMobileAdminAuditRoute: ApiMobileAdminAuditRoute,
  ApiMobileAdminEmployeesRoute: ApiMobileAdminEmployeesRouteWithChildren,
  ApiMobileAuthMeRoute: ApiMobileAuthMeRoute,
  ApiMobilePushRegisterRoute: ApiMobilePushRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
